// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgn5q_-uLxsEe-GJ-z8LI3kpMQ7ckYm5Y',
    appId: '1:487460222471:web:fa3667a13d14a888851ca2',
    messagingSenderId: '487460222471',
    projectId: 'live-stock-f3138',
    authDomain: 'live-stock-f3138.firebaseapp.com',
    databaseURL: 'https://live-stock-f3138-default-rtdb.firebaseio.com',
    storageBucket: 'live-stock-f3138.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDODj7bOUJo9RooA-FAGsJc78qmg2mgtw',
    appId: '1:487460222471:android:0c3d39e275680764851ca2',
    messagingSenderId: '487460222471',
    projectId: 'live-stock-f3138',
    databaseURL: 'https://live-stock-f3138-default-rtdb.firebaseio.com',
    storageBucket: 'live-stock-f3138.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-J3Za25rzpnB7IupZM1RV9FkxvFBQ70',
    appId: '1:487460222471:ios:684827587b8f0ab1851ca2',
    messagingSenderId: '487460222471',
    projectId: 'live-stock-f3138',
    databaseURL: 'https://live-stock-f3138-default-rtdb.firebaseio.com',
    storageBucket: 'live-stock-f3138.appspot.com',
    iosClientId: '487460222471-u7q36pdh6j0kkl466c60587n86f9cl05.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifcation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-J3Za25rzpnB7IupZM1RV9FkxvFBQ70',
    appId: '1:487460222471:ios:684827587b8f0ab1851ca2',
    messagingSenderId: '487460222471',
    projectId: 'live-stock-f3138',
    databaseURL: 'https://live-stock-f3138-default-rtdb.firebaseio.com',
    storageBucket: 'live-stock-f3138.appspot.com',
    iosClientId: '487460222471-u7q36pdh6j0kkl466c60587n86f9cl05.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifcation',
  );
}
